<?php
/**
 * @var $block \Softnoesis\RelatedProduct\Block\Module
 */
?>
<?php
  $productcollection = $block->getProductcollection();
  $isEnable = $block->getConfigValue();
if ($isEnable == 1):
?> 
  <div class="content-heading">
    <h2 class="title"><?php echo $block->getTitleValue();?></h2>
  </div>
  <section id="demos">
    <div class="brand-list-wrapper">
      <div class="owl-carousel owl-theme">
        <?php foreach ($productcollection as $key => $product): ?>
          <div class="item">
           <div class="product-item-info" data-container="product-grid"> 
            <div class="cdz-hover-section">
              <div class="cdz-product-top">
                <a href="<?php echo $product->getProductUrl();?>" class="product photo product-item-photo" tabindex="-1">
                  <div class="main-image">
                    <img class="images" src="<?php echo $block->getMediaUrl().'catalog/product'.$product->getThumbnail();?>">
                  </div>
                </a>
              </div>
            </div>
            <div class="product details product-item-details">
                <span class="product name product-item-name">
                  <a class="product-item-link" href="<?php echo $product->getProductUrl();?>">
                    <?php echo $product->getName();?>
                  </a>
                </span>
                <div class="price-box price-final_price">
                    <span class="price-container price-final_price tax weee">
                      <span class="price-wrapper">
                        <span class="price"><?php echo $block->getSymbol();?><?php echo number_format((float)$product->getPrice(), 2, '.', '');?></span>
                      </span>
                     </span>
                </div>
            </div>
          </div>
          </div>
        <?php endforeach; ?>
         <div class="column view-more">
            <a href="<?php echo $block->getCurrentCategoryUrl();?>">View More</a>
         </div>
      </div>
    </div>
  </section>
<?php endif; ?>
<script>
  require([
    'jquery',
    'Softnoesis_RelatedProduct/js/owl.carousel',
  ], function($) {
    jQuery(document).ready(function() {
      var owl = $('.owl-carousel');
      owl.owlCarousel({
        margin: 10,
        nav: true,
        loop: false,
        dots: true,
        nav: false,
        responsive: {
          0: {
            items: 1
          },
          600: {
            items: 3
          },
          1000: {
            items: 5
          }
        }
      });
    });
  });
</script>
